### ISSUE TITLE
Add an example to setup a custom Chrony configuration

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-docs#122]
Write an example FCCT config to setup a custom NTP server for Chrony.

**Comment by travier** [comment]
Example:
```
storage:
  files:
    - path: /etc/chrony.conf
      overwrite: yes
      mode: 0644
      contents:
        inline: |
          ...
```
