### ISSUE TITLE
Document with_mount_unit from Butane

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-docs#125]
People get the mount units wrong a lot. Let's document [our helper](https://github.com/coreos/fcct/issues/48) that makes things much easier. Example:

```
variant: fcos
version: 1.1.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAA...
storage:
  disks:
    - device: /dev/sda
      partitions:
        - number: 0
          label: var-log
          size_mib: 0
          start_mib: 0
  filesystems:
    - device: /dev/disk/by-partlabel/var-log
      path: /var/log
      format: xfs
      wipe_filesystem: true
      with_mount_unit: true
```
