### ISSUE TITLE
document how to set a hostname via fcct/ignition

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-docs#129]
Something like this should work:

```
variant: fcos
version: 1.1.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - $sshpubkey
storage:
  files:
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: |
          ignitionhostname
```
