### ISSUE TITLE
Document how to configure the docker daemon from FCCT

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-docs#130]
See https://docs.docker.com/engine/reference/commandline/dockerd.
E.g. to pick a few common ones: changing the log driver, debug mode, and insecure registries.

Would be nice to use [configuration files](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file), but it doesn't support drop-ins, so isn't very friendly to FCOS.

The `moby-engine` package we ship uses `/etc/sysconfig/docker` as an environment file for the daemon systemd unit. It's clunky but probably the cleanest approach for now is to do similarly to what's described in https://github.com/coreos/fedora-coreos-tracker/issues/588 and add a systemd unit override to just redefine `ExecStart` so we can append arbitrary flags.

(Though we should also look into what are the upstream plans for supporting a config overlay paradigm.)

**Comment by J0WI** [comment]
Here is an example for Ignition:
```
systemd:
  units:
    - name: docker.service
      dropins:
        - name: 10-debug.conf
          contents: |
            [Service]
            Environment=DOCKER_OPTS="--debug"
            ExecStart=
            ExecStart=/usr/bin/dockerd --host=fd:// --exec-opt native.cgroupdriver=systemd $OPTIONS $DOCKER_OPTS
```

**Comment by dghubble** [comment]
To add declarative examples, you can also just overwrite the `/etc/sysconfig/docker` file. Since Docker unfortunately doesn't support configuration drop-ins.

```yaml
variant: fcos
version: 1.0.0
storage:
  files:
    - path: /etc/sysconfig/docker
      overwrite: true
      contents:
        inline: |
          # Modify these options if you want to change the way the docker daemon runs
          OPTIONS="--selinux-enabled \
            --log-driver=json-file \
            --live-restore \
            --default-ulimit nofile=65536:65536 \
            --init-path /usr/libexec/docker/docker-init \
            --userland-proxy-path /usr/libexec/docker/docker-proxy \
          "
```
