### ISSUE TITLE
document fcct local files features

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-docs#163]
This might exist but I couldn't find it easily so I'll just put this here. We should add some examples of the `local` files feature of `fcct`:

```
variant: fcos
version: 1.1.0
storage:
  # call with --files-dir=/path/to/files/zram-generator
  trees:
    - local: fakeroot
```

```
$ tree /path/to/files/zram-generator/fakeroot/
/path/to/files/zram-generator/fakeroot
└── etc
    └── systemd
        ├── system
        │   └── swap-create@.service
        ├── system-generators
        │   └── zram-generator
        └── zram-generator.conf
$ cat fcct_zram_generator.yaml | fcct --files-dir=/path/to/files/zram-generator
```

Another example this time merging configs:

```
variant: fcos
version: 1.1.0
ignition:
  config:
    merge:
      - local: ./generated-files/master.ign
```

```
cat resources/fcct-control-plane.yaml | fcct -d ./ -o ./generated-files/control-plane-processed.ign
```
