### ISSUE TITLE
document how to enable linger for a user

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-docs#205]
A user may want a user unit to run on boot without them having to log in. `sudo loginctl enable-linger $USER` exists for this but running commands doesn't fit the model very well.

You can achieve the same goal as `sudo loginctl enable-linger $USER` by creating an empty file in `/var/lib/systemd/linger/$USER`. So for the `core` user it would be: 

```
variant: fcos
version: 1.1.0
storage:
  files:
    - path: /var/lib/systemd/linger/core
      mode: 0644
      contents: 
        inline: ''
```
