### ISSUE TITLE
user-level systemd unit example: /home/sleeper/.config is owned by root

### ISSUE THREAD

**Issue by eriksjolund** [coreos/fedora-coreos-docs#367]
Regarding the example

https://docs.fedoraproject.org/en-US/fedora-coreos/tutorial-user-systemd-unit-on-boot/#_writing_the_butane_config_and_converting_to_ignition

```
variant: fcos
version: 1.4.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa ...
    - name: sleeper
storage:
  directories:
    - path: /home/sleeper/.config/systemd/user/default.target.wants
      mode: 0744
      user:
        name: sleeper
      group:
        name: sleeper
  files:
    - path: /var/lib/systemd/linger/sleeper
      mode: 0644
    - path: /home/sleeper/.config/systemd/user/linger-example.service
      mode: 0755
      contents:
        inline: |
          [Unit]
          Description=A systemd user unit demo
          After=network-online.target
          Wants=network-online.target
          [Service]
          ExecStart=/usr/bin/sleep infinity
      user:
        name: sleeper
      group:
        name: sleeper
  links:
    - path: /home/sleeper/.config/systemd/user/default.target.wants/linger-example.service
      user:
        name: sleeper
      group:
        name: sleeper
      target: /home/sleeper/.config/systemd/user/linger-example.service
      hard: false
```
The butane configuration does not explicitly create _/home/sleeper/.config_. 
That leads to the directory being owned by root.

```
[esjolund@laptop fedora-coreos-docs]$ ssh  -p 2222 -o NoHostAuthenticationForLocalhost=true core@127.0.0.1
Fedora CoreOS 35.20220213.1.0
Tracker: https://github.com/coreos/fedora-coreos-tracker
Discuss: https://discussion.fedoraproject.org/tag/coreos

[core@localhost ~]$ sudo -i
[root@localhost ~]# ls -ld /home/sleeper/.config/
drwxr-xr-x. 3 root root 21 Feb 17 22:18 /home/sleeper/.config/
[root@localhost ~]# 
```

The directory should instead be owned by _sleeper:sleeper_
