### ISSUE TITLE
Document growing /boot

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-docs#410]
See https://github.com/coreos/fedora-coreos-tracker/issues/1196

Will need to come with a warning but this could be useful for debugging.

**Comment by skewballfox** [comment]
the suggestion didn't work for me, at least not with the installation I was using. I created this script
```bash
#!/bin/bash
set -euo pipefail

DISK=/dev/sdb

BOOT_DELTA_MIB=640 
ESP_DELTA_MIB=1920   
TOTAL_DELTA_MIB=$(( BOOT_DELTA_MIB + ESP_DELTA_MIB ))

ESP_DELTA_SECTORS=$(( ESP_DELTA_MIB * 2048 ))
BOOT_DELTA_SECTORS=$(( BOOT_DELTA_MIB * 2048 ))
TOTAL_DELTA_SECTORS=$(( BOOT_DELTA_SECTORS + ESP_DELTA_SECTORS ))

# Back up existing ESP contents and metadata
mkdir -p /tmp/esp_bak /tmp/boot_bak
mount "${DISK}2" /mnt 2>/dev/null && cp -a /mnt/* /tmp/esp_bak/ && umount /mnt
mount "${DISK}3" /mnt 2>/dev/null && cp -a /mnt/* /tmp/boot_bak/ && umount /mnt


# Capture the exact original UUID to maintain GRUB/fstab mapping integrity
ESP_UUID=$(blkid -o value -s UUID "${DISK}2")
BOOT_UUID=$(blkid -o value -s UUID "${DISK}3")


get_field() { sfdisk -J "$DISK" | jq -r ".partitiontable.partitions[] | select(.node==\"${DISK}${1}\") | .${2}"; }

S3=$(get_field 3 start); SZ3=$(get_field 3 size)
S4=$(get_field 4 start); SZ4=$(get_field 4 size)

NEW_S4=$(( S4 + TOTAL_DELTA_SECTORS ))
NEW_S3=$(( S3 + ESP_DELTA_SECTORS ))
NEW_SZ3=$(( SZ3 + BOOT_DELTA_SECTORS ))

# Move 4 first — into free space at the tail of the disk
echo "${NEW_S4},${SZ4}" | sfdisk --move-data "$DISK" -N 4
# Then move 3 — into the space 4 just vacated
echo "${NEW_S3},${NEW_SZ3}" | sfdisk --move-data "$DISK" -N 3
# Now grow the ESP into the space 3 just vacated
sfdisk "$DISK" -N 2 <<< ", +${ESP_DELTA_MIB}M"

blockdev --rereadpt "$DISK"
udevadm settle

# Format but FORCE the exact original volume UUID 
# This stops GRUB and ignition discovery mechanisms from breaking
mkfs.vfat -F32 -i "${ESP_UUID//-/}" -n EFI-SYSTEM "${DISK}2"
mkfs.ext4 -U "$BOOT_UUID" -L boot "${DISK}3"

udevadm settle

mount --source "${DISK}2" /mnt && cp -a /tmp/esp_bak/* /mnt/ && umount /mnt
mount --source "${DISK}3" /mnt && cp -a /tmp/boot_bak/* /mnt/ && umount /mnt
```
and then passed  it with `coreos-installer iso customize --post-install` 
```bash
butane --strict --output server.ign server.bu &&\ 
coreos-installer iso customize \
  --dest-ignition server.ign \
  --dest-device /dev/sdb \
  --post-install resize-esp.sh \
  --live-karg-append="systemd.setenv=SYSTEMD_SULOGIN_FORCE=1" \
  --output server-final.iso \ 
  fedora-coreos-44.20260607.3.1-live-iso.x86_64.iso
```
the only thing I did in the butane file was set the root to only be 16G
```yaml
  disks:
    - device: /dev/disk/by-id/coreos-boot-disk
      wipe_table: false
      partitions:
        - label: root
          number: 4
          wipe_partition_entry: true
          type_guid: 4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709
  filesystems:
    - device: /dev/disk/by-partlabel/root
      format: xfs
      label: root
      wipe_filesystem: true
```
p.s. this wouldn't work as a service on first boot, because those run after the root partition has been resized

when I tried the approach of explicitly setting the sizes of efi, boot, with the above, the system was unbootable I'm guessing because the wipefs happened after the efi boot was configured
