### ISSUE TITLE
Document setting the keyboard layout

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-docs#454]
Something like this should work:

```yaml
variant: fcos
version: 1.4.0
storage:
  files:
    - path: /etc/vconsole.conf
      contents:
        inline: |
           KEYMAP=fr-latin1
           FONT=eurlatgr
```
