### ISSUE TITLE
Add docs examples for "LUKS volumes with discard option & perf-no_read_workqueue/perf-no_write_workqueue"

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-docs#512]
See:
- https://github.com/coreos/fedora-coreos-tracker/issues/1392
- https://github.com/coreos/ignition/pull/1540

**Comment by travier** [comment]
We should also probably split the LUKS Storage configuration part into its own page.

**Comment by feidens** [comment]
For the meantime if one needs a full (butane yaml) example see below. If I can help writing the documentation in some form then let me know.

```
variant: fcos
version: 1.5.0
passwd:
  users:
    - name: core
      ssh_authorized_keys_local:
        - your_key_file.pub
storage:
  disks:
   - device: /dev/vda
     partitions:
       - label: root
         number: 4
         # 0 means to use all available space
         size_mib: 0
         resize: true
  luks:
    - name: root
      label: luks-root
      device: /dev/disk/by-partlabel/root
      clevis:
        tpm2: true
      # key_file:
      #  local: luks.key
      wipe_volume: true
      discard: true
      options:
        - --pbkdf=argon2id
      open_options:
        - --perf-no_read_workqueue
        - --perf-no_write_workqueue
  filesystems:
    - device: /dev/mapper/root
      format: xfs
      wipe_filesystem: true
      label: root
```

FYI: Without the `storage.disks.partitions` part the Growth step failed.
