### ISSUE TITLE
[Document Request] Time Zone and/or Ability to Execute Command

### ISSUE THREAD

**Issue by f35f0ef9d0e827dae86552d3899f78fc** [coreos/fedora-coreos-docs#59]
I believe below is how you can 1) run any shell command during installation and 2) set the timezone of the machine. I think it would be helpful if this kind of information was spelled out in the documentation over at https://docs.fedoraproject.org/en-US/fedora-coreos/

This is technically a systemd service, but it only runs once. Seems an odd way to set the timezone to me, but I am not sure how else to do it in the fcc file.

```
systemd:
  units:
    - name: settimezone.service
      enabled: true
      contents: |
        [Unit]
        Description=Set the time zone

        [Service]
        ExecStart=/usr/bin/timedatectl set-timezone Europe/Paris
        RemainAfterExit=yes
        Type=oneshot
        
        [Install]
        WantedBy=multi-user.target

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
Well, this is the syntax I am using.
```
storage:
  links:
    - path: /etc/localtimer
      target: ../usr/share/zoneinfo/America/Chicago
```

This is the result after installation:
```
ls -lh /etc/localtimer 
lrwxrwxrwx. 1 root root 37 Mar 12 19:13 /etc/localtimer -> ../usr/share/zoneinfo/America/Chicago
```

But when I run the `date` command, I get a UTC time. So, then I run
`sudo timedatectl set-timezone America/Chicago`

which results in:
```
ls -lh /etc/localtimer 
lrwxrwxrwx. 1 root root 37 Mar 12 14:13 /etc/localtimer -> ../usr/share/zoneinfo/America/Chicago
```

And that dependably works. I cannot see why the symlink method is not working.

**Comment by jlebon** [comment]
It's `/etc/localtime` (without the `r` at the end).

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
Thank you! I missed that even though I was looking back and forth several times. This worked:

```
storage:
  links:
    - path: /etc/localtime
      target: ../usr/share/zoneinfo/America/Chicago
```
