### ISSUE TITLE
Document how to change SSH port (and other settings)

### ISSUE THREAD

**Issue by jbtrystram** [coreos/fedora-coreos-docs#649]
I tried to do this : 
```
variant: fcos
version: 1.5.0
systemd:
  units:
    - name: sshd.socket
      dropins:
        - name: custom-port.conf
          contents: |
              [Socket]
              ListenStream=2222
```

But this has no effect.
